# SPDX-FileCopyrightText: 2021 CERN.
# SPDX-License-Identifier: MIT

[pytest]
addopts = --isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=citeproc_styles --cov-report=term-missing
testpaths = tests citeproc_styles
live_server_scope = module
